### ISSUE TITLE
Need to remove the readme file

### ISSUE THREAD

**Issue by AnirudhDaya** [4N1Z/Sorting-Searching-Algorithms#51]
In this [folder](https://github.com/4N1Z/Sorting-Searching-Algorithms/tree/main/Searching/Fibonacci%20Search)
There is a readme file which is not needed. We want to copy the contents of the readme file and paste them as comments in this [file](https://github.com/4N1Z/Sorting-Searching-Algorithms/blob/main/Searching/Fibonacci%20Search/in_Java.java).

**Comment by Kesav890** [comment]
can i have this issue?

**Comment by AnirudhDaya** [comment]
Yes sure go ahead!
