### ISSUE TITLE
Wish to add a few Important applications of Searching Algos

### ISSUE THREAD

**Issue by priyanshuhaldar007** [4N1Z/Sorting-Searching-Algorithms#82]
Add a java program to find the ceiling of the target number from the given array with time complexity of O(nlogn) using binary search. Please assign me this issue.

**Comment by AnirudhDaya** [comment]
@4N1Z  do we need this?

**Comment by ashish2675** [comment]
@priyanshuhaldar007 i have pulled this check for it

**Comment by 4N1Z** [comment]
Hey Pal,
Great to have your contribution, but we only require the algorithms for searching and sorting and we do not accept questions. 

Happy coding!
